//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whitelist
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string PrimaryRoleId { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
    }
}
